site_name: IA · Portfolio — Alexia Aurrecochea
site_description: Portfolio personal de proyectos de IA, datos y sistemas embebidos
site_url: https://<tu-usuario>.github.io/IA-PORTFOLIO-1/
repo_url: https://github.com/<tu-usuario>/IA-PORTFOLIO-1
repo_name: IA-PORTFOLIO-1
site_dir: site

theme:
  name: material
  language: es
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs 
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - content.code.copy
  palette:
        - scheme: default
          primary: custom
          accent: custom
          toggle:
            icon: material/weather-night
            name: Modo oscuro
        - scheme: slate
          primary: custom
          accent: custom
          toggle:
            icon: material/white-balance-sunny
            name: Modo claro
extra_css:
  - assets/extra.css


plugins:
  - search
  - awesome-pages
  - macros 
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - footnotes
  - toc:
      permalink: true
      toc_depth: 2-3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true         # dibuja los checkboxes bonitos
      clickable_checkbox: true      # opcional: permite clicarlos (no persiste)



edit_uri: blob/main/docs/

extra_css:
  - assets/extra.css

nav:
  - Inicio: index.md
  - "Acerca de mí": acerca.md
  - Portfolio:
      - Índice: portfolio/index.md
      - "01 — Análisis Exploratorio del dataset Iris": "portfolio/Práctica1.md"
      - "02 — Publicación del Portafolio": "portfolio/Práctica2.md"
      - "03 — EDA de Netflix con pandas": "portfolio/Práctica3.md"
      - "04 — EDA Multifuentes + Joins": "portfolio/Práctica4.md"
  - Recursos: recursos.md


