site_name: IA · Portfolio — Alexia Aurrecochea
site_description: Portfolio personal de proyectos de IA, datos y sistemas embebidos
site_url: https://<tu-usuario>.github.io/IA-PORTFOLIO-1/
repo_url: https://github.com/<tu-usuario>/IA-PORTFOLIO-1
repo_name: IA-PORTFOLIO-1
site_dir: site

theme:
  name: mkdocs-material
  language: es
  logo: assets/placeholder.png
  favicon: assets/placeholder.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

edit_uri: blob/main/docs/

theme:
  palette:
    - scheme: default
      primary: custom
      accent: custom

extra_css:
  - assets/extra.css

